version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=sqlite:///./employees.db
  api:
  build: .
  depends_on:
    - db
  restart: always
  environment:
    DATABASE_URL: postgresql://user:password@db/employees_db
  ports:
    - "8000:8000"
  command: uvicorn main:app --host 0.0.0.0 --port 8000